- id: '1589530554082'
  alias: Make announcement on alexa
  description: ''
  trigger:
  - entity_id: input_boolean.switch
    platform: state
  condition:
  - condition: state
    entity_id: input_boolean.switch
    state: 'on'
  action:
  - data:
      data:
        type: announce
      message: '{{ states("input_text.message") }}'
      target:
      - media_player.office_echo
      - media_player.kitchen_echo_dot
    service: notify.alexa_media
  - data: {}
    entity_id: input_boolean.switch
    service: input_boolean.turn_off
  - data:
      value: Ding Dong!
    service: notify.mobile_app_sm_n976v
